The First Task is completed
YehorAltShuler/coffee_delivery_app pull request #1
Opened 2023-01-09 13:22 UTC by YehorAltShuler

Bottom Navigation Bar & Screens have been aded

2023-01-09 13:40 UTC, YehorAltShuler commented
UI specifications:
https://www.figma.com/file/qMnX1YMS15Hu3vXTSvlPVH/Coffee-Delivery-App-Exploration-(Community)?node-id=1%3A2

Technical specifications: 
- Create an App
- Add Bottom Navigation Bar
- Add 4 Screens with text that contains title in it

2023-01-10 20:44 UTC, ldemyanenko commented
Please add one widget test that checks MainPage. It should check that this page has bottom navigation bar with 4 items in it. It should be able to click each one and check corresponding text

2023-01-10 20:45 UTC, ldemyanenko requested changes

2023-01-10 20:45 UTC, ldemyanenko commented on lib/main.dart
> +        scaffoldBackgroundColor: const Color(0xFF201520),
Could you move all the colors you are using in the separate file/class? Try checking best practices in this

2023-01-10 20:45 UTC, ldemyanenko commented on lib/widgets/main_navigator.dart
> +        unselectedItemColor: Color(0xFF746863),
Same comment as above about colors

2023-01-10 20:54 UTC, ldemyanenko requested changes

2023-01-10 20:54 UTC, ldemyanenko commented on lib/widgets/main_navigator.dart
> +  List<Widget> _screens = [
I suggest not to put widgets in a list variable without a good reason

2023-01-10 20:54 UTC, ldemyanenko commented on lib/widgets/main_navigator.dart
> +          BottomNavigationBarItem(icon: Icon(Icons.home), label: ''),
Use const key word where possible

2023-01-10 20:54 UTC, ldemyanenko commented on lib/widgets/main_navigator.dart
> +            label: '',
No need to set empty string there and in all other items here

2023-01-12 18:08 UTC, YehorAltShuler commented on lib/main.dart
> +        scaffoldBackgroundColor: const Color(0xFF201520),
Made a file with constant colors.

2023-01-12 18:10 UTC, YehorAltShuler commented on lib/widgets/main_navigator.dart
> +  List<Widget> _screens = [
Moved widgets from variable to children of BottomNavBar

2023-01-12 18:11 UTC, YehorAltShuler commented on lib/widgets/main_navigator.dart
> +          BottomNavigationBarItem(icon: Icon(Icons.home), label: ''),
Did it

2023-01-12 18:13 UTC, YehorAltShuler commented on lib/widgets/main_navigator.dart
> +            label: '',
I have to, otherwise there will be an error

2023-02-02 09:04 UTC, ldemyanenko approved these changes

2023-02-06 17:02 UTC, YehorAltShuler commented
Merging Task-1 into master

2023-02-06 17:03 UTC, merged