Aded Products Grid
YehorAltShuler/coffee_delivery_app pull request #2
Opened 2023-02-07 08:41 UTC by YehorAltShuler

2023-02-10 20:50 UTC, ldemyanenko requested changes

2023-02-21 17:03 UTC, YehorAltShuler commented on lib/widgets/card_product_image.dart
> +          ClipRRect(
Ok, I removed it

2023-02-21 17:27 UTC, YehorAltShuler commented on lib/widgets/product_card.dart
> +class _ProductCardState extends State<ProductCard> {
Ok, changed it to Stateless

2023-02-22 07:17 UTC, YehorAltShuler commented on lib/providers/product.dart
> +  double rate;
I think it have to become a provider soon

2023-02-23 11:31 UTC, YehorAltShuler commented on lib/providers/product.dart
> +  void toggleFavoriteStatus() {
Since I don't use this code I'd better delete it for now.

2023-02-24 20:11 UTC, ldemyanenko commented on lib/providers/product.dart
> +  double rate;
The correct structure should be Model -> Service -> Provider
Model is immutable and represents the data. Services represents different groups of actions - data base service or api service or shared preferences service.  Provider extends ChangeNotifier and represents app state and actions with it

2023-02-24 20:13 UTC, ldemyanenko commented on lib/providers/product.dart
> +  double rate;
You mixed Provider(State) and  Data model together.

2023-02-24 20:20 UTC, ldemyanenko commented on lib/providers/product.dart
> +  double rate;
Currently we don't have what I called services

2023-02-27 10:30 UTC, YehorAltShuler commented on lib/widgets/card_product_add.dart
> +    return ClipRRect(
Ok, done

2023-02-27 10:31 UTC, YehorAltShuler commented on lib/widgets/card_product_image.dart
> +    return ClipRRect(
+

2023-02-27 10:31 UTC, YehorAltShuler commented on lib/screens/home_screen.dart
> -      appBar: AppBar(title: const Text('Home Screen')),
Finaly did it

2023-03-08 07:38 UTC, YehorAltShuler commented on lib/main.dart
> +          fontFamily: 'Centaur',
+

2023-03-13 13:35 UTC, ldemyanenko requested changes

2023-03-13 14:00 UTC, YehorAltShuler commented on lib/widgets/card_product_add.dart
> +            child: ClipRRect(
For cutting Material corners

2023-03-13 14:00 UTC, YehorAltShuler commented on lib/widgets/card_product_add.dart
> +              child: Material(
Cause it's a buttons ancestor

2023-03-13 15:34 UTC, YehorAltShuler commented on lib/widgets/card_product_add.dart
> +            child: ClipRRect(
but no more needed

2023-03-13 15:38 UTC, ldemyanenko approved these changes

2023-03-13 16:53 UTC, merged