Make a page of product details by clicking on the product
YehorAltShuler/coffee_delivery_app pull request #3
Opened 2023-03-02 22:48 UTC by YehorAltShuler

https://www.figma.com/file/qMnX1YMS15Hu3vXTSvlPVH/Coffee-Delivery-App-Exploration-(Community)?node-id=1%3A2&t=KyRzNP9sccntBmMZ-0

2023-03-03 20:48 UTC, ldemyanenko requested changes

2023-03-03 20:48 UTC, ldemyanenko commented on lib/main.dart
> +      create: (BuildContext context) => Products(),
Yes, usually you initiate global app state providers in this place

2023-03-03 20:48 UTC, ldemyanenko commented on lib/screens/ProductDetails/product_details_screen.dart
> +    final product = ModalRoute.of(context)?.settings.arguments as Product;
Taking arguments in this place will force this operation on every build. Where did you find this practice? @YehorAltShuler

2023-03-03 20:48 UTC, ldemyanenko commented on lib/screens/ProductDetails/product_details_screen.dart
> +                            Icons.arrow_back,
You should use asset from design. This arrow is different. Same for other material icons

2023-03-03 20:48 UTC, ldemyanenko commented on lib/screens/ProductDetails/product_details_screen.dart
> +                ReadMoreText(
nice

2023-03-03 20:48 UTC, ldemyanenko commented on lib/widgets/ProductCard/card_product_add.dart
> +                style: Theme.of(context)
I would suggest ass font family to the Theme definition. I doubt that the same TextStyle is used in design with different font families

2023-03-03 20:48 UTC, ldemyanenko commented on lib/widgets/input_chips.dart
> +class InputChip extends StatefulWidget {
Is not used in project

2023-03-03 20:57 UTC, YehorAltShuler commented on lib/screens/ProductDetails/product_details_screen.dart
> +    final product = ModalRoute.of(context)?.settings.arguments as Product;
Uuuh... Just saw this everywhere in tutorials

2023-03-08 21:50 UTC, YehorAltShuler commented on lib/screens/ProductDetails/product_details_screen.dart
> +                ReadMoreText(
+

2023-03-08 21:54 UTC, YehorAltShuler commented on lib/widgets/input_chips.dart
> +class InputChip extends StatefulWidget {
I deleted it

2023-03-13 15:43 UTC, YehorAltShuler commented on lib/screens/ProductDetails/product_details_screen.dart
> +                            Icons.arrow_back,
+

2023-03-13 15:48 UTC, YehorAltShuler commented on lib/widgets/ProductCard/card_product_add.dart
> +                style: Theme.of(context)
there is 2 font families in dsign definitely.

2023-03-17 16:14 UTC, ldemyanenko commented on lib/widgets/ProductCard/card_product_add.dart
> +                style: Theme.of(context)
Yes, but are they used in same TextStyle combinations? Anyway it's doesn't looks good to define theme in this way. Try defining them on app theme level

2023-03-17 16:23 UTC, ldemyanenko commented on lib/screens/ProductDetails/product_details_screen.dart
> +    final product = ModalRoute.of(context)?.settings.arguments as Product;
Looks like Flutter team doesn't mind such an approach https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments

2023-03-19 18:16 UTC, YehorAltShuler commented on lib/widgets/ProductCard/card_product_add.dart
> +                style: Theme.of(context)
You was right, it seems like Open sans uses for body Text

2023-03-27 16:57 UTC, ldemyanenko approved these changes

2023-03-27 16:57 UTC, ldemyanenko commented on lib/main.dart
> +                headlineSmall: const TextStyle(color: Colors.white),
nice

2023-03-28 07:37 UTC, merged