Task 4
YehorAltShuler/coffee_delivery_app pull request #5
Opened 2023-03-18 20:56 UTC by YehorAltShuler

https://www.figma.com/file/qMnX1YMS15Hu3vXTSvlPVH/Coffee-Delivery-App-Exploration-(Community)?node-id=1-2

Add search bar with filtering function on home tab

2023-03-29 07:41 UTC, ldemyanenko requested changes

2023-03-29 07:41 UTC, ldemyanenko commented on lib/providers/products_provider.dart
> +  late List<Product> filteredProducts = [..._items];
Why did you use `late` keyword ?

2023-03-29 07:41 UTC, ldemyanenko commented on lib/screens/home_screen/product_card/search_bar.dart
> +        results = products
I don't see why should we have additional stored variable filteredProducts rather then searchText and use getter for filtered products

2023-03-29 07:41 UTC, ldemyanenko commented on lib/screens/home_screen/product_card/search_bar.dart
> +            .filterProductList(results);
It doesn't look clear to use filtered product variable in case there is no filter

2023-03-31 07:48 UTC, YehorAltShuler commented on lib/providers/products_provider.dart
> +  late List<Product> filteredProducts = [..._items];
there is an error withot it - The instance member '_items' can't be accessed in an initializer.
Try replacing the reference to the instance member with a different expression

I don't know why

2023-04-01 10:03 UTC, YehorAltShuler commented on lib/screens/home_screen/product_card/search_bar.dart
> +            .filterProductList(results);
Yes, i refactor logi and moved it into provider file

2023-04-04 09:44 UTC, ldemyanenko commented on lib/providers/products_provider.dart
> +  late List<Product> filteredProducts = [..._items];
I see. Weird.  But it looks like this is legit way to do this

2023-04-04 09:46 UTC, ldemyanenko commented on lib/screens/home_screen/product_card/search_bar.dart
> +            .filterProductList(results);
Why are you storing _filterredProduct variable instead of using getter get filterredProducts => products
          .where((product) =>
              product.title.toLowerCase().contains(enterdKeyword.toLowerCase()))
          .toList() for this?

2023-04-04 09:52 UTC, ldemyanenko commented on test/search_bar_test.dart
> +    final productCard = find.byKey(
As see this test doesn't check the search functionality. It checks the text field and that there are product cards(they might be there on other reasons). You need some dynamic case there. Check something before search and after, and show from results that this difference explains the search logic.

2023-04-18 08:44 UTC, YehorAltShuler commented on lib/screens/home_screen/product_card/search_bar.dart
> +        results = products
Yes, we should not

2023-04-18 09:22 UTC, YehorAltShuler commented on test/search_bar_test.dart
> +    final productCard = find.byKey(
ok, i added a check before typing a text in search field

2023-05-01 15:13 UTC, ldemyanenko commented on test/search_bar_test.dart
> +    final productCard = find.byKey(
Looks much better now. Unfortunately it fails for me(a one more test fails with it)

2023-05-01 15:24 UTC, ldemyanenko approved these changes

2023-05-17 15:41 UTC, merged